#!/bin/bash

source AHCAL_env.sh

printf '\033[1;32;48m \t STARTING DAQ LOCALLY\033[0m \n'
echo $(date)
printf '\033[22;33m\t Cleaning up first...  \033[0m \n'

if [ -f KILLRUN.local ]
then
    sh KILLRUN.local
else
    sh KILLRUN
fi

cd $DATADIR

printf '\033[22;33m\t  caliceProducer-scintillator  \033[0m \n'
$EUDAQBIN/AHCALProducer -n CaliceSc -r tcp://$HOSTIP:$RCPORT | tee $EUDAQDIR/logs/calice_ahcal_producer.log&
#-r tcp://$HOSTIP:$RCPORT &
sleep 3



printf ' \n'
printf ' \n'
printf ' \n'
printf '\033[1;32;48m\t ...Done!\033[0m \n'
printf '\033[1;32;48mSTART OF DAQ COMPLETE\033[0m \n'
