#!/bin/bash

source AHCAL_env.sh

printf '\033[1;32;48m \t STARTING DAQ LOCALLY\033[0m \n'
echo $(date)
printf '\033[22;33m\t Cleaning up first...  \033[0m \n'

if [ -f KILLRUN.local ]
then
    sh KILLRUN.local
else
    sh KILLRUN
fi

printf '\033[22;31m\t End of killall \033[0m \n'

sleep 1

ls

######################################################################
#if [ -n "`ls data/run*.raw`" ]
#then
#    printf '\033[22;33m\t Making sure all data files are properly writeprotected \033[0m \n'
#    chmod a=rw data/run*.raw
#    printf '\033[22;32m\t ...Done!\033[0m \n'
#fi

cd $DATADIR

#=====================================================================
printf '\033[22;33m\t Starting Subprocesses \033[0m \n'
#=====================================================================

printf '\033[22;33m\t  caliceProducer-scintillator  \033[0m \n'
$EUDAQBIN/AHCALProducer -n CaliceSc -r tcp://192.168.21.1:$RCPORT &
#-r tcp://$HOSTIP:$RCPORT &
sleep 3



printf ' \n'
printf ' \n'
printf ' \n'
printf '\033[1;32;48m\t ...Done!\033[0m \n'
printf '\033[1;32;48mSTART OF DAQ COMPLETE\033[0m \n'
